apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infra-bot-data
  namespace: infra-bot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-nvme
  resources:
    requests:
      storage: 1Gi
